### PR TITLE
Minor README grammar and type fixes

### PR DESCRIPTION
**Pull request by holsee**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@holsee Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/gen-batch-server&pullRequestId=12)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/gen-batch-server&pullRequestId=12) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by kjnilsson** [comment]
Thanks!

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
Approved without refreshing the page 😆. Thank you, @holsee!

**Comment by pivotal-issuemaster** [comment]
@holsee Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/gen-batch-server&pullRequestId=12)!

**Pull request merged**
